# Generated by Django 5.1.3 on 2025-03-10 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_priority_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
    ]
